# Generated by Django 4.0.3 on 2022-04-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potion',
            name='color',
            field=models.CharField(choices=[('https://i.imgur.com/P51dKQT.png', 'Purple'), ('https://i.ibb.co/DKFNktT/pinkpotion.png', 'Pink'), ('https://i.ibb.co/DGTKdkP/bluepotion.png', 'Blue'), ('https://i.ibb.co/dj74TPm/greenpotion.png', 'Green'), ('https://i.ibb.co/YNxF730/redpotion.png', 'Red'), ('https://i.ibb.co/FbbXxCc/yellowpotion.png', 'Yellow'), ('https://i.ibb.co/b6tjYr2/orangepotion.png', 'Orange')], default='https://i.imgur.com/P51dKQT.png', max_length=100),
        ),
    ]
