# Generated by Django 4.0.3 on 2022-04-04 16:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_alter_potions_ingredients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Potions',
            new_name='Potion',
        ),
    ]
