# Generated by Django 4.0.2 on 2022-04-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_ingredient_image_ingredient_picture_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='picture_upload',
            new_name='image',
        ),
    ]
