# Generated by Django 4.0.2 on 2022-04-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_picture_upload_ingredient_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.CharField(blank=True, default='https://pngset.com/images/white-question-mark-question-mark-white-number-symbol-text-transparent-png-1022201.png', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='potion',
            name='color',
            field=models.CharField(max_length=16),
        ),
    ]
