# Generated by Django 4.0.2 on 2022-04-05 21:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_ingredient_image_alter_potion_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='potion',
            name='ingredients',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='image',
            field=models.CharField(blank=True, default='https://s3-us-west-2.amazonaws.com/potionmaster/b20738.png', max_length=2000, null=True),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(1))),
                ('ingredient', models.ManyToManyField(to='main_app.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='potion',
            name='recipe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.recipe'),
        ),
    ]
