# Generated by Django 4.0.2 on 2022-04-05 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_potion_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potion',
            name='recipe',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.recipe'),
        ),
    ]
