# Generated by Django 4.0.3 on 2022-04-06 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_remove_potion_recipe_ingredientquantity_potion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientQuantity',
            new_name='Recipe',
        ),
    ]
